### ISSUE TITLE
can I get access to this on PyPI?

### ISSUE THREAD

**Issue by glyph** [mikeal/deferred#3]
I'd like to give the Twisted release team upload permissions so we can start migrating into different PyPI packages.

**Comment by mikeal** [comment]
I don't know if my login even still works, haven't logged into pypi for years. @cyisfor do you still have access?

**Comment by glyph** [comment]
@mikeal did you end up trying your login?  I am wondering if it's time to ask @dstufft for divine intercession yet

**Comment by mikeal** [comment]
@glyph ya, i still have no idea what it is, let me know what I can do to get someone on the admin side to intervene.

**Comment by dstufft** [comment]
@mikeal Does a `mikael.h****@gmail.com` email address ring a bell for you?

**Comment by mikeal** [comment]
@dstufft it should me mikeal dot rogers at gmail, emails here should still work.

**Comment by dstufft** [comment]
Ah, my bad, I transposed letters in the user name, that's the address I have on file for the user name. Let me send an email to verify.

**Comment by dstufft** [comment]
Ok, I've added @glyph to the entry on PyPI.

**Comment by glyph** [comment]
Thanks @dstufft, sorry for the admin overhead!

**Comment by glyph** [comment]
Fixed!
